[project]
name = "tempsens"
version = "0.1.0"
authors = [
  { name="Simen Bruøygard", email="simen.bruoy@gmail.com" },
]
description = "Temperature and humidity monitoring system for Raspberry Pi with DHT22 sensor"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "shiny",
    "shinywidgets",
    "numpy==1.26.4",
    "bokeh",
    "h5py==3.10",
    "psutil",
    "pandas",
    "jupyter-bokeh>=4.0.5",
]

[project.optional-dependencies]
pi = [
    "adafruit_dht",
]

