#!/usr/bin/env python3
"""
Setup script for initializing deployment configuration.

This script helps you set up deployment configs from templates,
ensuring sensitive data (IPs, credentials) stays local and gitignored.

Usage:
    python deployment/setup_deployment.py
"""

import configparser
from pathlib import Path
import shutil


def copy_template(template_path: Path, target_path: Path, force: bool = False):
    """Copy template file to target if target doesn't exist."""
    if target_path.exists() and not force:
        print(f"[SKIP] {target_path} already exists")
        return False

    shutil.copy(template_path, target_path)
    print(f"[OK] Created {target_path}")
    return True


def sync_server_config(deployment_config_path: Path, server_config_path: Path):
    """
    Generate server/config_server.ini from deployment/config_deployment.ini.

    This ensures both configs stay in sync without duplicating sensor lists.
    """
    if not deployment_config_path.exists():
        print(f"[SKIP] {deployment_config_path} doesn't exist yet")
        return

    deployment_config = configparser.ConfigParser()
    deployment_config.read(deployment_config_path)

    server_config = configparser.ConfigParser()

    # Copy SERVER section from deployment config
    if deployment_config.has_section('SERVER'):
        server_config.add_section('SERVER')
        for key, value in deployment_config.items('SERVER'):
            server_config.set('SERVER', key, value)

    # Copy SENSORS section from deployment config
    if deployment_config.has_section('SENSORS'):
        server_config.add_section('SENSORS')
        for key, value in deployment_config.items('SENSORS'):
            server_config.set('SENSORS', key, value)

    # Write server config
    with open(server_config_path, 'w') as f:
        server_config.write(f)

    print(f"[OK] Synced {server_config_path} from deployment config")


def main():
    repo_root = Path(__file__).parent.parent

    print("=== Temperature Sensor Deployment Setup ===\n")

    # 1. Copy deployment config template
    print("Step 1: Creating deployment config...")
    deployment_template = repo_root / 'deployment' / 'config_deployment.ini.template'
    deployment_config = repo_root / 'deployment' / 'config_deployment.ini'

    if copy_template(deployment_template, deployment_config):
        print(f"  -> Edit {deployment_config} and add your sensor IPs")

    # 2. Copy server config template
    print("\nStep 2: Creating server config...")
    server_template = repo_root / 'server' / 'config_server.ini.template'
    server_config = repo_root / 'server' / 'config_server.ini'

    if copy_template(server_template, server_config):
        print(f"  -> This will be auto-synced from deployment config")

    # 3. Copy client config template (for manual Pi setup)
    print("\nStep 3: Creating client config template...")
    client_template = repo_root / 'config.ini.template'
    client_config = repo_root / 'config.ini'

    if copy_template(client_template, client_config):
        print(f"  -> Edit {client_config} for local testing")
        print(f"  -> On Pis, this is auto-generated by Ansible")

    # 4. Sync deployment config to server config
    print("\nStep 4: Syncing configs...")
    sync_server_config(deployment_config, server_config)

    print("\n=== Setup Complete ===")
    print("\nNext steps:")
    print(f"  1. Edit {deployment_config}")
    print(f"     - Add your git repo URL")
    print(f"     - Add sensor names and Headscale IPs")
    print(f"  2. Run: python deployment/sync_configs.py")
    print(f"     - This syncs deployment config → server config")
    print(f"  3. Run: python deployment/generate_ansible_inventory.py")
    print(f"     - This generates Ansible inventory from sensor IPs")
    print(f"  4. Run: ./deployment/deploy.sh")
    print(f"     - This deploys to all sensors")
    print(f"\nFiles created are git-ignored and safe to commit templates.")


if __name__ == '__main__':
    main()
